### ISSUE TITLE
Add papers

### ISSUE THREAD

**Issue by KangqingYe** [liuyangme/SOTA-3DHPE-HMR#2]
Thank you for your work, and I suggest adding these papers to the 3D human pose estimation collection:

- VoxelPose [[paper]](https://arxiv.org/pdf/2004.06239.pdf) ECCV2020, Multi-person, Top-down
- ContextPose [[paper]](https://openaccess.thecvf.com/content/CVPR2021/papers/Ma_Context_Modeling_in_3D_Human_Pose_Estimation_A_Unified_Perspective_CVPR_2021_paper.pdf) CVPR21, Single-person, In Images, Solving Body Structure Understanding
- VoxelPose [[paper]](https://arxiv.org/pdf/2004.06239.pdf) ECCV2020, Multi-person, Top-down
- MvP [[paper]](https://proceedings.neurips.cc/paper_files/paper/2021/file/6da9003b743b65f4c0ccd295cc484e57-Paper.pdf) NIPS2021, Multi-person, Others, Single Stage
- MVGFormer [[paper]](https://arxiv.org/pdf/2311.10983.pdf) CVPR2024, Multi-person, Others, Single Stage

**Comment by liuyangme** [comment]
Thank you for your suggestion. If necessary, it will be updated on the next version of the project homepage. However, considering the page limit of the article, we can only introduce some typical work of various methods.
