### ISSUE TITLE
A typographical error in the paper

### ISSUE THREAD

**Issue by zearo-github** [liuyangme/SOTA-3DHPE-HMR#4]
![image](https://github.com/liuyangme/SOTA-3DHPE-HMR/assets/90169120/1ea7763c-f5d1-46b9-8f7e-dfe670d389ca)
The part shown by the red line is repeated.

**Comment by liuyangme** [comment]
Thank you for your meticulous review. We apologize for the oversight, which occurred during the transition to a different LaTeX template. This error has been addressed, and the corrected version will be available shortly. ❤️
